### ISSUE TITLE
Reveals: authenticate POST endpoint

### ISSUE THREAD

**Issue by sohkai** [aragonone/court-backend#114]
Right now, anyone from `court.aragon.org` can access the POST endpoint and send fake reveal information for another juror.

This would be terrible, especially if it overwrote previous information, as you could wipe the reveal information of a juror without them knowing—likely making that juror miss their reveal window.

**Comment by facuspagnuolo** [comment]
I guess we already talked about this, see https://github.com/aragonone/court-backend/blob/development/packages/server/src/validators/RevealsValidator.js#L44-L53

**Comment by sohkai** [comment]
Closing; the server will only accept requests if the salt matches a commitment available on-chain.

This means that a user could only send valid salts for another juror (and at that point they may want to penalize a leak instead), but it does mean that the frontend cannot send this POST request until the commitment transaction has been mined.
