### ISSUE TITLE
Contracts: Avoid multiple method definition warning

### ISSUE THREAD

**Issue by facuspagnuolo** [aragonone/court-backend#117]
Currently, ethers is warning with ` WARNING: Multiple definitions for [method]` when wrapping contracts

**Comment by facuspagnuolo** [comment]
Fixed by #125

**Comment by sohkai** [comment]
Was ethers giving that warning because we had overriden methods in the ABI?

**Comment by facuspagnuolo** [comment]
Yes

**Comment by sohkai** [comment]
Gotcha, this seems like the relevant thread then: https://github.com/ethers-io/ethers.js/issues/499
