### ISSUE TITLE
Shared: Migrate from axios to fetch

### ISSUE THREAD

**Issue by facuspagnuolo** [aragonone/court-backend#139]
Currently, in the back-office and the monitoring service we are using `axios` to perform HTTP requests, we can use `fetch` instead.

**Comment by sohkai** [comment]
Is there a reason to prefer `fetch`? `fetch` isn't available on Node by default (this is a browser-only built in) and we would have to polyfill it anyway with something like `isometric-fetch` or, more commonly, just using `axios`.

**Comment by facuspagnuolo** [comment]
@promaty suggested it, and I thought there was native support for `fetch`. If there isn't I wouldn't migrate then, we can close this
