### ISSUE TITLE
Add monitoring for failed transactions

### ISSUE THREAD

**Issue by sohkai** [aragonone/court-backend#209]
It would be ideal if we got infra alerts on transactions failing:

- Heartbeat: if two transactions have failed in the last 24h
- Reveal: on any transactions failing
- Settlement: if 3+ transactions failed in the last 24h

Timing is somewhat debatable.

**Comment by promaty** [comment]
Added metrics in #216 
This shows any type of transaction failing in the past 24 hours, we can define metrics on them in k8s manifests
