### ISSUE TITLE
Server, Service: immediately fail if database connection is incorrect

### ISSUE THREAD

**Issue by sohkai** [aragonone/court-backend#78]
Previously the server would continue running until an endpoint was hit where it needed to use the database.

We should sanity check at start up that the connections are indeed good, and fail immediately if not.

**Comment by bingen** [comment]
Hm, ok, I see that for the server, but for the services, there are some, like heartbeat or settlement of penalties, that don't need the database at all (and are quite critical). Wouldn't it be better to have them running even if reveal (which is the only one using it now) cannot?
